version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.8.5  # Let's update to 3.9 ASAP
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python server.py

  dbdata:
    image: busybox
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
      - /var/lib/postgresql/data

  db:
    image: postgres:13.0
    environment:
        APPLICATION_POSTGRES_DB: ${APPLICATION_POSTGRES_DB}
        APPLICATION_POSTGRES_USER: ${APPLICATION_POSTGRES_USER}
        APPLICATION_POSTGRES_PW: ${APPLICATION_POSTGRES_PW}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # for postgers user
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.8.5
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.4
